### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by tkwidmer** [clearlyandy/Taxee#3]
Can you enable HTTPS support for this, trying to use your api from a site that uses HTTPS and can't because of Mixed Content being blocked. This would make this API really useful.

**Comment by clearlyandy** [comment]
Hey @tkwidmer, 

Thanks for the interest in Taxee.  

Unfortunately, I am not invested enough in this service to put an SSL cert behind http://taxee.io.  I encourage you to use the code directly on your (https) site instead.
