### ISSUE TITLE
Data Source

### ISSUE THREAD

**Issue by JTronLabs** [clearlyandy/Taxee#4]
I apologize if this is addressed somewhere, and I haven't seen it. Where is this *.json data coming from? What is the original source for all this tax info? Thank you!

**Comment by andyhass-pr** [comment]
Hi @JTronLabs,

The source of the data isn't mentioned on taxee.io or in the current source code, but I'd be happy to share!  

The data was compiled manually from federal and state government websites/publications.  In the next major version of the Taxee API (coming out in late February), data source details will be included in the API responses and JSON data.

**Comment by JTronLabs** [comment]
Thank you for your response, great tool!
