### ISSUE TITLE
Data sources

### ISSUE THREAD

**Issue by thebradbain** [clearlyandy/Taxee#6]
I'm a huge fan of any essential open source API such as this! As it seems like you've moved on from this side project, do you mind sharing where you compiled the supporting data from? I'd like to manually update it (or perhaps even automate it).

**Comment by andyhass-pr** [comment]
Hi @thebradbain - thanks for your interest in Taxee.  

The data contained in this repo was compiled manually from federal and state government websites/publications. In the next major version of the Taxee API (coming out in the very near future), data source details will be included in the responses from the hosted API and in the JSON data contained in this repository.

At the moment, the process of manually compiling this data happens twice a year.  There isn't a consistent source of information (as the URLs of the government sites that change this data change) and state tax brackets change on unknown schedules - hence the manual process :(

Regarding updated data, the focus has been primarily on the hosted API over the past few months as it's usage has grown significantly.  This repo will be updated with new data soon!
