### ISSUE TITLE
NPM Package?

### ISSUE THREAD

**Issue by JTronLabs** [clearlyandy/Taxee#9]
I'd like to use the US tax information in a project of mine - any way to publish this data via NPM?

**Comment by clearlyandy** [comment]
@JTronLabs - coincidentally, the Taxee team was working on this today.  See https://github.com/taxee/taxee-tax-statistics - if you have any issues or comments, add them to that repository please.  Thanks!

**Comment by JTronLabs** [comment]
Awesome!

**Comment by JTronLabs** [comment]
[NPM link for posterity](https://www.npmjs.com/package/taxee-tax-statistics)
